version: 2

models:
  - name: int_open_age
    description: Modèle intermédiaire regroupant le pourcentage d'étudiants openclassroom par tranches d'âge et par an
    columns:
      - name: POURCENTAGE_AGE_OPENCLASSROOM
        description: Pourcentage des étudiants openclassroom classés par age et par an
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: ANNEE_DEBUT_FORMATION
        description: année des formations réalisées par les étudiants
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: FOURCHETTE_AGE_REGROUPEE
        description: fourchette d'âge des étudiants
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['15-24 ans', '25-49 ans', '50-64 ans']
  - name: int_open_genre
    description: Modèle intermédiaire regroupant le pourcentage d'étudiants openclassroom par genre et par an
    columns:
      - name: POURCENTAGE_GENRE_OPENCLASSROOM
        description: Pourcentage des étudiants openclassroom classés par genre et par an
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: ANNEE_DEBUT_FORMATION
        description: année des formations réalisées par les étudiants
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: GENRE
        description: genre que les étudiants ont indiqués. La donnée non renseignée par l'étudiant à été retirée
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['F','M']
  - name: int_open_regions
    description: Modèle intermédiaire regroupant le pourcentage d'étudiants openclassroom par région et par an
    columns:
      - name: POURCENTAGE_REGION_OPENCLASSROOM
        description: Pourcentage des étudiants openclassroom classés par région et par an
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: ANNEE_DEBUT_FORMATION
        description: année des formations réalisées par les étudiants
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: REGION
        description: région des étudiants
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: varchar
          - accepted_values:
              arguments:
                values: ['DROM','Bourgogne-Franche-Comté','Normandie','Centre-Val de Loire','Pays de la Loire','Bretagne',"Provence-Alpes-Côte d''Azur",'Nouvelle-Aquitaine','Corse','Occitanie','Grand Est','Hauts-de-France','Auvergne-Rhône-Alpes','Île-de-France']  
  - name: int_quantite_parcours
    description: Modèle intermédiaire regroupant le pourcentage d'étudiants openclassroom par région et par an
    columns:
      - name: NOMBRE_ETUDIANT_TOTAL
        description: Nombre d'étudiants openclassroom sur toutes les années
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
      - name: NOMBRE_USER_TOTAL_DOUBLON
        description: Nombre d'étudiants openclassroom ayant fait 2 formations ou plus
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
      - name: USER_DOUBLON_TOTAL_POURCENTAGE
        description: Pourcentage d'étudiants openclassroom ayant fait 2 formations ou plus
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
  - name: int_insee_genre_age_trt
    description: Modèle intermédiaire pour regrouper les données de l'INSEE afin de les classer par age, genre et année
    columns:
      - name: NOMBRE_PERSONNES
        description: Nombre de personnes en emplois classé par tranche d'âge et genre (en milliers de personnes)
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number   
      - name: ANNEE
        description: années pour les emplois
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: TRANCHE_AGE
        description: fourchettes d'âges des emplois nommées comme pour les données openclassroom 
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['15-24 ans', '25-49 ans', '50-64 ans'] 
      - name: GENRE
        description: genre pour les emplois nommées comme pour les données openclassroom 
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['F','M','Ensemble']
  - name: int_insee_age
    description: Modèle intermédiaire regroupant les données de l'INSEE pour le pourcentage d'emplois par age et par an
    columns:
      - name: POURCENTAGE_AGE_INSEE
        description: Pourcentage des emplois classés par age et par an
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: ANNEE
        description: années pour les emplois
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: TRANCHE_AGE
        description: fourchette d'âge des emplois
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['15-24 ans', '25-49 ans', '50-64 ans']
  - name: int_insee_genre
    description: Modèle intermédiaire regroupant les données de l'INSEE pour le pourcentage d'emplois par genre et par an
    columns:
      - name: POURCENTAGE_GENRE_INSEE
        description: Pourcentage des emplois classés par genre et par an
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: ANNEE
        description: années pour les emplois
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: GENRE
        description: genre pour les emplois
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['F','M']
  - name: int_insee_regions
    description: Modèle intermédiaire regroupant les données de l'INSEE pour le pourcentage d'emplois par régions et par an (2022, 2023 et 2024)
    columns:
      - name: POURCENTAGE_REGION_INSEE
        description: Pourcentage des emplois classés par région et par an.
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: REGION_FINALE
        description: régions pour les emplois. Retravaillé pour correspondre avec les régions indiquées par openclassroom
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: varchar
          - accepted_values:
              arguments:
                values: ['DROM','Bourgogne-Franche-Comté','Normandie','Centre-Val de Loire','Pays de la Loire','Bretagne',"Provence-Alpes-Côte d''Azur",'Nouvelle-Aquitaine','Corse','Occitanie','Grand Est','Hauts-de-France','Auvergne-Rhône-Alpes','Île-de-France']  
      - name: ANNEE
        description: annees des emplois les régions. Il n'y a que 2024
        data_tests:
          - not_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
