name: 'Openclassrooms'
version: '1.0.0'
config-version: 2

profile: 'snowflake_data'
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  analyse_openclassrooms_socio:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts: 
      +materialized: table
