version: 2

models:
  - name: mrt_OPEN_INSEE
    description: Modèle marts regroupant toutes les données INSEE et Openclassroom 
    columns:
      - name: ANNEE
        description: années pour les emplois de l'INSEE et les formations des étudiants
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
          - dbt_expectations.expect_column_value_lengths_to_equal:
              arguments: 
                value: 4
      - name: TRANCHE_AGE
        description: fourchette d'âge pour les emplois de l'INSEE et les formations des étudiants
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['15-24 ans', '25-49 ans', '50-64 ans']
      - name: GENRE
        description: genre pour les emplois de l'INSEE et les formations des étudiants
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['F','M']
      - name: NOMBRE_ETUDIANT_TOTAL
        description: Nombre d'étudiants openclassroom sur toutes les années
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
      - name: NOMBRE_USER_TOTAL_DOUBLON
        description: Nombre d'étudiants openclassroom ayant fait 2 formations ou plus
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments: 
                column_type: Number
      - name: USER_DOUBLON_TOTAL_POURCENTAGE
        description: Pourcentage d'étudiants openclassroom ayant fait 2 formations ou plus
        data_tests:
          - not_null        
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: POURCENTAGE_AGE_OPENCLASSROOM
        description: Pourcentage des étudiants openclassroom classés par age et par an
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: POURCENTAGE_GENRE_OPENCLASSROOM
        description: Pourcentage des étudiants openclassroom classés par genre et par an
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: POURCENTAGE_REGION_OPENCLASSROOM
        description: Pourcentage des étudiants openclassroom classés par région sur l'année 2024
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: POURCENTAGE_AGE_INSEE
        description: Pourcentage des emplois classés par age et par an
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: POURCENTAGE_GENRE_INSEE
        description: Pourcentage des emplois classés par genre et par an
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: POURCENTAGE_REGION_INSEE
        description: Pourcentage des emplois classés par région sur l'année 2024
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100
      - name: REGION
        description: Régions pour les emplois de l'INSEE et les formations des étudiants
